# -*- coding: utf-8 -*-
"""AI chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mYlpFv7NjHDIs73UeA254L2_6cl-uNmc
"""

import nltk
import random
import string
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet, stopwords

nltk.download('punkt')
nltk.download('wordnet')
nltk.download('stopwords')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def normalize_text(text):
    tokens = nltk.word_tokenize(text.lower())
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in string.punctuation and word not in stop_words]
    return tokens

intents = {
    "greeting": {
        "patterns": ["hello", "hi", "hey", "good morning", "good evening"],
        "responses": ["Hello!", "Hi there!", "Hey!", "Greetings!"]
    },
    "goodbye": {
        "patterns": ["bye", "goodbye", "see you", "take care"],
        "responses": ["Goodbye!", "See you later!", "Take care!"]
    },
    "thanks": {
        "patterns": ["thanks", "thank you", "appreciate it"],
        "responses": ["You're welcome!", "No problem!", "Anytime!"]
    },
    "age": {
        "patterns": ["how old are you", "your age", "when were you created"],
        "responses": ["I'm timeless!", "I'm a bot, age doesn't apply to me."]
    },
    "name": {
        "patterns": ["what is your name", "who are you", "your name"],
        "responses": ["I'm a Python chatbot.", "You can call me ChatBot."]
    }
}

def match_intent(user_input):
    input_tokens = normalize_text(user_input)
    for intent, data in intents.items():
        for pattern in data['patterns']:
            pattern_tokens = normalize_text(pattern)
            if any(word in input_tokens for word in pattern_tokens):
                return intent
    return None

def get_response(user_input):
    intent = match_intent(user_input)
    if intent:
        return random.choice(intents[intent]['responses'])
    else:
        return "I'm not sure how to respond to that."

def chat():
    print("ChatBot: Hello! Type 'exit' to end.")
    while True:
        user_input = input("You: ")
        if user_input.lower() in ["exit", "quit", "bye"]:
            print("ChatBot: Goodbye!")
            break
        response = get_response(user_input)
        print(f"ChatBot: {response}")

if __name__ == "__main__":
    chat()